on: 
  push:
    branches:
      - master
name: ğŸš€ Implementar sistema no push
jobs:
  web-deploy:
    name: ğŸ‰ Implementando alteraÃ§Ãµes
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Pegando Ãºltimo cÃ³digo
      uses: actions/checkout@v2
    
    - name: ğŸ“‚ Sincronizando arquivos
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.ftp_host }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}
        server-dir: catalogon.genesisdevstudio.com/